### ISSUE TITLE
Cannot install make-license version 0.5

### ISSUE THREAD

**Issue by adabru** [accraze/make-license#104]
Hi, I can not install version 0.5.

```
npm i make-license@^0.4
make-license
```

Works fine.

```
npm i make-license@^0.5
```

Generates error:

```
npm ERR! argv "/home/adabru/.nvm/versions/node/v7.4.0/bin/node" "/home/adabru/.nvm/versions/node/v7.4.0/bin/npm" "i" "make-license@^0.5"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! path /home/adabru/Desktop/Apps/word-complete/node_modules/make-license/dist/index.sh
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/adabru/Desktop/Apps/word-complete/node_modules/make-license/dist/index.sh'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/adabru/Desktop/Apps/word-complete/node_modules/make-license/dist/index.sh'
```

I am on Ubuntu 16.04.

**Comment by accraze** [comment]
Hey @adabru thanks for the heads up! Is this related to #9 ?

**Comment by adabru** [comment]
It may be. I tried a few things:

```
# download make-license
npm pack make-license
tar -xf make-license-0.5.0.tgz
```

Running `npm install ./package` gives error as described in first comment. 

```
cd package
npm install
npm run build
```

Running `./dist/index.sh` gives error
```
import inquirer from "inquirer";
^^^^^^
SyntaxError: Unexpected token import
```

After googling (https://stackoverflow.com/a/33608835/6040478)

```
babel src --out-dir dist --presets es2015
```

`./dist/index.sh` now works fine

As `npm install ./package` was complaining about `no such file or directory, chmod '../node_modules/make-license/dist/index.sh'` I replaced
```
  "files": [
    "src"
  ],
```
with
```
  "files": [
    "src", "dist"
  ],
```
in ./package.json

```
cd ..
npm install ./package
```
So now it works.

Summary:
- adding `"dist"` as to the package.json files and adding `--presets es2015` to the babel build command gives me a working program
- executing index.js without babel does not work `Syntax error: import ... from ...`, and probably shouldn't at the moment[¹](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c)
