### ISSUE TITLE
Add codecov badge to README

### ISSUE THREAD

**Issue by accraze** [accraze/make-license#75]
https://codecov.io/gh/accraze/make-license

**Comment by kgraves** [comment]
I'll take this one!

**Comment by jvdub** [comment]
Created a PR: #77

**Comment by jvdub** [comment]
Sorry, @kgraves! I just started working on it and was done by the time I saw you were taking it. Feel free to have a look at my PR create a new one if there's an improvement to be made!

**Comment by kgraves** [comment]
@jvdub no problem

**Comment by accraze** [comment]
resolved by #77
