### ISSUE TITLE
Option for naming the file UNLICENSE

### ISSUE THREAD

**Issue by adabru** [accraze/make-license#8]
Thank you for this package. I'd like to have the possibility of naming the file UNLICENSE when choosing the according license. This is their official recommendation: http://unlicense.org/

**Comment by accraze** [comment]
That's a great idea! Will push up a fix for this a little later in the week.

**Comment by accraze** [comment]
Hey @adabru I've added an option to name an unlicense file `UNLICENSE`... thanks again for the great suggestion! The feature is in the most recent release (v0.2.0) on npm :grin:

**Comment by adabru** [comment]
Thank you very much, it works nice! There is another problem that came up for me and I created a new issue.
