### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by adabru** [accraze/make-license#9]
Hello, when trying to run `./node_modules/make-license/src/index.js/`, I'm told `/usr/bin/env: node --harmony: No such file or directory`. Probably it is the same problem as described [here](http://stackoverflow.com/questions/8108917/why-does-passing-arguments-to-the-command-in-an-env-invocation-not-work). Removing the string `--harmony` solves the problem for me. I am using Ubuntu.

**Comment by accraze** [comment]
Hey @adabru thanks for raising this issue. I'm on Mac OSX, so the `--harmony` didn't cause any problems for me... If you figure out a cross-platform solution, a PR would be awesome! :smile:

**Comment by accraze** [comment]
closed by commit 3ec31efb22fd44b01ef0525c6d2a363a4ed556e1
